# Generated by Django 5.1.2 on 2025-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название метки'),
        ),
    ]
