# Generated by Django 5.1.2 on 2025-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='chips',
            field=models.ManyToManyField(blank=True, related_name='cards', to='main.chip', verbose_name='Метки/Чипы'),
        ),
    ]
