# Generated by Django 5.1.2 on 2025-05-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_offset_minutes', models.IntegerField(blank=True, null=True, verbose_name='Предыдущее смещение (минуты)')),
                ('new_offset_minutes', models.IntegerField(blank=True, null=True, verbose_name='Новое смещение (минуты)')),
                ('action', models.CharField(choices=[('created', 'Создано напоминание'), ('updated', 'Изменено напоминание'), ('disabled', 'Отключено пользователем'), ('auto_disabled', 'Автоматически отключено при выполнении'), ('sent', 'Напоминание отправлено'), ('failed', 'Ошибка отправки напоминания'), ('cancelled', 'Отменено из-за удаления карточки')], max_length=20, verbose_name='Действие')),
                ('timezone_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часовой пояс пользователя')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent браузера')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('card_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения карточки на момент действия')),
                ('reminder_calculated_time', models.DateTimeField(blank=True, null=True, verbose_name='Вычисленное время напоминания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='main.card', verbose_name='Карточка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог напоминания',
                'verbose_name_plural': 'Логи напоминаний',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['card', 'timestamp'], name='main_remind_card_id_68443c_idx'), models.Index(fields=['user', 'timestamp'], name='main_remind_user_id_e7090d_idx'), models.Index(fields=['action', 'timestamp'], name='main_remind_action_7e1190_idx'), models.Index(fields=['timestamp'], name='main_remind_timesta_729aea_idx')],
            },
        ),
    ]
