# Generated by Django 5.1.2 on 2025-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AddField(
            model_name='card',
            name='date_time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
        migrations.AddField(
            model_name='card',
            name='reminder_calculated_time',
            field=models.DateTimeField(blank=True, help_text='Автоматически рассчитывается на основе времени завершения и смещения', null=True, verbose_name='Вычисленное время напоминания (UTC)'),
        ),
        migrations.AddField(
            model_name='card',
            name='reminder_offset_minutes',
            field=models.IntegerField(blank=True, help_text='За сколько минут до завершения отправить напоминание', null=True, verbose_name='Смещение напоминания (минуты)'),
        ),
    ]
