# Generated by Django 5.0.4 on 2024-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_board_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='chip',
        ),
        migrations.AddField(
            model_name='chip',
            name='card',
            field=models.ManyToManyField(blank=True, default=None, to='main.card', verbose_name='Card'),
        ),
    ]
