# Generated by Django 5.0.4 on 2024-04-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_card_chip_chip_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Color')),
                ('color_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Color name')),
                ('card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.card')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
