# Generated by Django 5.0.4 on 2024-04-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chipcolor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChipColor',
            new_name='Color',
        ),
    ]
