# Generated by Django 5.0.4 on 2024-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_chipcolor_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='card',
        ),
        migrations.AddField(
            model_name='color',
            name='card',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.card'),
        ),
    ]
