# Generated by Django 5.0.4 on 2024-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_chip_color_remove_color_card_color_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='chip',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='chip', to='main.chip'),
        ),
    ]
