# Generated by Django 5.0.4 on 2024-04-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_color_chip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='chip',
        ),
        migrations.AddField(
            model_name='color',
            name='chip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chip', to='main.chip'),
        ),
    ]
