# Generated by Django 5.0.4 on 2024-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_color_chip_color_chip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='chip',
        ),
        migrations.AddField(
            model_name='chip',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Chip color'),
        ),
        migrations.AddField(
            model_name='chip',
            name='mame_color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name chip color'),
        ),
    ]
