# Generated by Django 5.0.4 on 2024-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_color_chip_chip_color_chip_mame_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='cover_color',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Cover color'),
        ),
    ]
