# Generated by Django 5.0.4 on 2024-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_color_cover_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='cover_color',
        ),
        migrations.AddField(
            model_name='color',
            name='color_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Color number'),
        ),
        migrations.AddField(
            model_name='color',
            name='hover_color',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Hover color'),
        ),
    ]
