# Generated by Django 5.0.4 on 2024-04-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_color_cover_color_color_color_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='mame_color',
        ),
    ]
