# Generated by Django 5.0.4 on 2024-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_chip_mame_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='color',
        ),
        migrations.AddField(
            model_name='chip',
            name='color_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Chip color number'),
        ),
    ]
