# Generated by Django 5.0.4 on 2024-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_card_status_alter_card_position_in_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Status'),
        ),
    ]
