# Generated by Django 5.0.4 on 2024-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='color_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Chip color number'),
        ),
    ]
