# Generated by Django 5.0.4 on 2024-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_chip_color_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_time_reminder',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
