# Generated by Django 5.0.4 on 2024-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_card_date_time_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_reminder',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Remind'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start'),
        ),
    ]
