# Generated by Django 5.0.4 on 2024-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_card_checklist_how_many_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, default='0001-01-01T00:00:00Z', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_reminder',
            field=models.DateTimeField(blank=True, default='0001-01-01T00:00:00Z', null=True, verbose_name='Remind'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_start',
            field=models.DateTimeField(blank=True, default='0001-01-01T00:00:00Z', null=True, verbose_name='Start'),
        ),
    ]
