# Generated by Django 5.0.4 on 2024-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_card_date_time_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, default='1970-01-01T00:00:00.000Z', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_reminder',
            field=models.DateTimeField(blank=True, default='1970-01-01T00:00:00.000Z', null=True, verbose_name='Remind'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_time_start',
            field=models.DateTimeField(blank=True, default='1970-01-01T00:00:00.000Z', null=True, verbose_name='Start'),
        ),
    ]
