# Generated by Django 5.0.4 on 2024-05-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userprofile_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_information',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active_board',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Активная доска'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фото пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Роль'),
        ),
    ]
