# Generated by Django 5.0.4 on 2024-05-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_column_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='main.board', verbose_name='На какой доске'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название колонки'),
        ),
        migrations.AlterField(
            model_name='column',
            name='position_on_board',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Позиция на доске'),
        ),
    ]
