# Generated by Django 5.0.4 on 2024-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_board_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='column',
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='column_name', to='main.column', verbose_name='Column'),
        ),
    ]
