# Generated by Django 5.0.4 on 2024-05-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_card_column_card_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='position_in_column',
        ),
        migrations.CreateModel(
            name='CardInColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_column', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_in_columns', to='main.card')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.column')),
            ],
            options={
                'unique_together': {('card', 'column')},
            },
        ),
    ]
