# Generated by Django 5.0.4 on 2024-05-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_card_position_in_column_cardincolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='column',
        ),
    ]
