# Generated by Django 5.0.4 on 2024-05-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_card_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardincolumn',
            old_name='card',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='cardincolumn',
            old_name='column',
            new_name='column_id',
        ),
        migrations.AlterUniqueTogether(
            name='cardincolumn',
            unique_together={('card_id', 'column_id')},
        ),
    ]
