# Generated by Django 5.0.4 on 2024-05-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_card_cardincolumn_card_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardincolumn',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardincolumn',
            old_name='column_id',
            new_name='column',
        ),
        migrations.AlterUniqueTogether(
            name='cardincolumn',
            unique_together={('card', 'column')},
        ),
    ]
