# Generated by Django 5.1 on 2024-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_card_id_cardincolumn_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='chips',
            field=models.ManyToManyField(blank=True, default=None, to='main.chip', verbose_name='Chip'),
        ),
    ]
