# Generated by Django 5.1 on 2024-10-20 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_chip_card_card_chips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник'), ('guest', 'Гость')], default='member', max_length=50, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='main.board', verbose_name='Доска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в доске',
                'verbose_name_plural': 'Участия в досках',
                'unique_together': {('user', 'board')},
            },
        ),
    ]
