# Generated by Django 5.1.2 on 2024-11-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_board_is_active_remove_board_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.board', verbose_name='Активная доска'),
        ),
    ]
